- name: DO deploy 
  hosts: all 
  become: yes
  tasks:
    - name: Find Old deployments
      find:
        paths: /home/student/apache-tomcat-8.5.50/webapps
        file_type: any
      register: OUT 

    - name: Delete all old files 
      file:
        path: "{{item.path}}"
        state: absent
      loop: "{{OUT.files}}"
      become: yes 

    - name: Download new war file 
      get_url:
        url: "{{URL}}"
        dest: /home/student/apache-tomcat-8.5.50/webapps/student.war 
      become_user: student 
